spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          order: 1
          predicates:
            - Path=/api/users/**
        - id: profile-service
          uri: http://user-service:8081
          order: 1
          predicates:
            - Path=/api/profile/**
        - id: product-service
          uri: http://product-service:8082
          order: 1
          predicates:
            - Path=/api/products/**
        - id: cart-service
          uri: http://cart-service:8083
          order: 1
          predicates:
            - Path=/api/cart/**
        - id: category-service
          uri: http://product-service:8082
          order: 1
          predicates:
            - Path=/api/categories/**
        - id: order-service
          uri: http://order-service:8084
          order: 1
          predicates:
            - Path=/api/orders/**
        - id: admin-orders
          uri: http://order-service:8084
          order: 1
          predicates:
            - Path=/api/admin/orders/**
        - id: admin-dashboard
          uri: http://order-service:8084
          order: 1
          predicates:
            - Path=/api/admin/dashboard/**
        - id: payment-service
          uri: http://payment-service:8085
          order: 1
          predicates:
            - Path=/api/payments/**
        - id: notification-service
          uri: http://notification-service:8086
          order: 1
          predicates:
            - Path=/api/notifications/**
        - id: delivery-orders
          uri: http://order-service:8084
          order: 1
          predicates:
            - Path=/api/delivery/**
        - id: delivery-service
          uri: http://delivery-service:8087
          order: 2
          predicates:
            - Path=/api/deliveries/**
        - id: analytics-service
          uri: http://analytics-service:8088
          order: 1
          predicates:
            - Path=/api/analytics/**
        - id: websocket-service
          uri: http://notification-service:8086
          order: 1
          predicates:
            - Path=/ws/**
