server:
  port: 8080

spring:
  application:
    name: revcart-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: user-service
          uri: http://localhost:8081
          order: 1
          predicates:
            - Path=/api/users/**
        - id: profile-service
          uri: http://localhost:8081
          order: 1
          predicates:
            - Path=/api/profile/**
        - id: product-service
          uri: http://localhost:8082
          order: 1
          predicates:
            - Path=/api/products/**
        - id: cart-service
          uri: http://localhost:8083
          order: 1
          predicates:
            - Path=/api/cart/**
        - id: category-service
          uri: http://localhost:8082
          order: 1
          predicates:
            - Path=/api/categories/**
        - id: order-service
          uri: http://localhost:8084
          order: 1
          predicates:
            - Path=/api/orders/**
        - id: admin-orders
          uri: http://localhost:8084
          order: 1
          predicates:
            - Path=/api/admin/orders/**
        - id: admin-dashboard
          uri: http://localhost:8084
          order: 1
          predicates:
            - Path=/api/admin/dashboard/**
        - id: payment-service
          uri: http://localhost:8085
          order: 1
          predicates:
            - Path=/api/payments/**
        - id: notification-service
          uri: http://localhost:8086
          order: 1
          predicates:
            - Path=/api/notifications/**
        - id: delivery-service
          uri: http://localhost:8087
          order: 1
          predicates:
            - Path=/api/delivery/**
        - id: analytics-service
          uri: http://localhost:8088
          order: 1
          predicates:
            - Path=/api/analytics/**
        - id: websocket-service
          uri: http://localhost:8086
          order: 1
          predicates:
            - Path=/ws/**


jwt:
  secret: revcart-secret-key-for-jwt-token-generation-and-validation-2024

resilience4j:
  circuitbreaker:
    instances:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
